[package]
name = "HexTwitchR"
description = "HexChat plugin for Twitch Chat integration over IRC"
version = "0.1.0-dev0"
authors = ["Yaulendil <davarice@protonmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"

[dependencies.hexchat]
path = "../hexchat-rs"

[lib]
name = "hextwitchr"
crate-type = ["cdylib"]
