[package]
name = "HexTwitchR"
description = "HexChat plugin for Twitch Chat integration over IRC"
version = "0.1.0-dev0"
authors = ["Davarice <davarice@protonmail.com>"]
edition = "2018"

[dependencies]
hexchat-plugin = "0.2.13"

[lib]
name = "hextwitchr"
crate-type = ["dylib"]
