[package]
name = "hextwitchr"
description = "HexChat plugin for Twitch integration over IRC"
version = "1.14.0-b1"
authors = ["Yaulendil"]
repository = "https://github.com/yaulendil/hextwitchr"
edition = "2018"
readme = "README.md"
keywords = ["hexchat", "xchat", "twitch", "irc", "plugin"]
license = "GPL-3.0"


[dependencies]
cached = "0.19.0"
chrono = "0.4"
hexchat = { git = "https://github.com/Yaulendil/hexchat-rs" }
parking_lot = { version = "0.11" } #features = ["nightly"] }


[lib]
name = "hextwitchr"
crate-type = ["cdylib", "rlib"]


[features]
nightly = []
strict-reward-uuids = []


[profile.release]
lto = true
codegen-units = 1
