[package]
name = "HexTwitchR"
description = "HexChat plugin for Twitch Chat integration over IRC"
version = "0.8.0-b0"
authors = ["Yaulendil <davarice@protonmail.com>"]
repository = "https://github.com/yaulendil/hextwitchr"
edition = "2018"
readme = "README.md"
keywords = ["hexchat", "xchat", "twitch", "irc", "chat", "plugin"]

[dependencies]
chrono = "0.4"
parking_lot = { version = "0.7.1", features = ["nightly"] }

[dependencies.hexchat]
git = "https://github.com/Yaulendil/hexchat-rs"

[lib]
name = "hextwitchr"
crate-type = ["cdylib"]
