[package]
name = "HexTwitchR"
description = "HexChat plugin for Twitch integration over IRC"
version = "1.0.5"
authors = ["Yaulendil"]
repository = "https://github.com/yaulendil/hextwitchr"
edition = "2018"
readme = "README.md"
keywords = ["hexchat", "xchat", "twitch", "irc", "plugin"]
license = "GPL-3.0"

[dependencies]
chrono = "0.4"
hexchat = { git = "https://github.com/Yaulendil/hexchat-rs" }
parking_lot = { version = "0.7.1", features = ["nightly"] }

[lib]
name = "hextwitchr"
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
